spring:
  application:
    name: springboot-init
  #\u6FC0\u6D3B\u914D\u7F6E\uFF0C\u9ED8\u8BA4dev
  profiles:
      active: dev
  # \u6587\u4EF6\u4E0A\u4F20
  servlet:
    multipart:
      # \u5927\u5C0F\u9650\u5236
      max-file-size: 10MB
  # session \u914D\u7F6E
  session:
    # todo \u53D6\u6D88\u6CE8\u91CA\u5F00\u542F\u5206\u5E03\u5F0F session\uFF08\u987B\u5148\u914D\u7F6E Redis\uFF09
    # store-type: redis
    # 30 \u5929\u8FC7\u671F
    timeout: 2592000
# mysql \u914D\u7F6E
# todo \u9700\u914D\u7F6EMysql  \u5BF9\u9F50spring\uFF1A\u4E0B
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/my_db
#    username: root
#    password: 123456

# redis \u914D\u7F6E
# todo \u9700\u914D\u7F6ERedis   \u5BF9\u9F50spring\uFF1A\u4E0B
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456

server:
  port: 8894
  servlet:
    context-path: /api
    # cookie 30 \u5929\u8FC7\u671F
    session:
      cookie:
        max-age: 2592000

# Mybatis-plus \u914D\u7F6E
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # \u5168\u5C40\u903B\u8F91\u5220\u9664\u7684\u5B9E\u4F53\u5B57\u6BB5\u540D
      logic-delete-value: 1 # \u903B\u8F91\u5DF2\u5220\u9664\u503C\uFF08\u9ED8\u8BA4\u4E3A 1\uFF09
      logic-not-delete-value: 0 # \u903B\u8F91\u672A\u5220\u9664\u503C\uFF08\u9ED8\u8BA4\u4E3A 0\uFF09

# \u5BF9\u8C61\u5B58\u50A8 \u914D\u7F6E
# todo \u9700\u66FF\u6362\u914D\u7F6E
#cos:
#  client:
#    host: xxx
#    accessKey: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx

# springdoc-openapi  knife4j \u914D\u7F6E
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.grey.springbootinit.controller
# knife 4j \u7684\u589E\u91CF\u914D\u7F6E
knife4j:
  enable: true
  setting:
    language: zh_cn
